# Generated by Django 3.2.24 on 2024-07-16 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_variant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.variant'),
        ),
    ]
